FROM python:3.9-alpine

WORKDIR /app

RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install oci-cli && \
    cp /usr/local/lib/python3.9/site-packages/oci_cli/bin/oci_autocomplete.sh /usr/local/bin/oci_autocomplete.sh && \
    chmod +x /usr/local/bin/oci_autocomplete.sh && \
    echo '[[ -e "/usr/local/bin/oci_autocomplete.sh" ]] && source "/usr/local/bin/oci_autocomplete.sh"' >> /etc/bash.bashrc
