{{- $release_name := .Release.Name }}
{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}

{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ $release_name }}-{{ $job.name }}"
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
spec:
  schedule: {{ $job.schedule | quote }}
  concurrencyPolicy: {{ $job.concurrencyPolicy | default "Forbid" | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ $job.name }}
              image: "{{ $job.image.repository }}:{{ $job.image.tag }}"
              imagePullPolicy: {{ $job.image.pullPolicy }}
              {{- with $job.command }}
              command: {{ toYaml . | nindent 16 }}
              {{- end }}
              {{- with $job.args }}
              args: {{ toYaml . | nindent 16 }}
              {{- end }}
              {{- with $job.env }}
              env: {{ toYaml . | nindent 16 }}
              {{- end }}
              envFrom:
                - secretRef:
                    name: {{ include "helm.fullname" $ }}
              {{- with $job.resources }}
              resources: {{ toYaml . | nindent 16 }}
              {{- end }}
              {{- with $job.volumeMounts }}
              volumeMounts: {{ toYaml . | nindent 16 }}
              {{- end }}
          restartPolicy: {{ $job.restartPolicy | default "Never" | quote }}
          {{- with $job.volumes }}
          volumes: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.nodeSelector }}
          nodeSelector: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.affinity }}
          affinity: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.tolerations }}
          tolerations: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.securityContext }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.serviceAccountName }}
          serviceAccountName: {{ . }}
          {{- end }}
          {{- with $job.serviceAccount }}
          serviceAccount: {{ . }}
          {{- end }}

  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit | default 3 }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit | default 1 }}
{{- end }}
