apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: vaultwarden
type: Opaque
data:
  PAR_URL: {{ .Values.oci.par_url | b64enc | quote }}
