apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: vaultwarden
type: Opaque
data:
  PAR_URL: {{ .Values.oci.par_url | b64enc | quote }}
  VW_SERVER: {{ .Values.vaultwarden.server_url | b64enc | quote }}
  VW_ID: {{ .Values.vaultwarden.client_id | b64enc | quote }}
  VW_TOKEN: {{ .Values.vaultwarden.client_secret | b64enc | quote }}
  VW_MASTER: {{ .Values.vaultwarden.master_password | b64enc | quote }}
  BW_ID: {{ .Values.bitwarden.client_id | b64enc | quote }}
  BW_TOKEN: {{ .Values.bitwarden.client_secret | b64enc | quote }}
  BW_MASTER: {{ .Values.bitwarden.master_password | b64enc | quote }}
