name: Publish Docker image (oci-cli)

on:
  push:
    branches: [ "master" ]
    paths:
      - "Dockerfile.oci-cli"
      - ".github/workflows/build-docker-oci-cli.yml"

env:
  DOCKER_REPO: "limejuny/oci-cli"
  DOCKER_USERNAME: "limejuny"
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.oci-cli
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ github.run_number }}
            ${{ env.DOCKER_REPO }}:latest
          platforms: linux/amd64,linux/arm64
