name: Publish Docker image

on:
  push:
    branches: [ "master" ]
    paths:
      - "Dockerfile"
      - ".github/workflows/docker-build.yml"

env:
  DOCKER_REPO: ${{ env.DOCKER_REPO }}
  DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ github.run_number }}
            ${{ env.DOCKER_REPO }}:latest
          platforms: ${{ matrix.arch }}
